# Generated by Django 3.2.1 on 2021-05-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magzine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magzine',
            name='image',
        ),
    ]
