# Generated by Django 3.2.1 on 2021-05-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ex4Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(max_length=5)),
            ],
        ),
    ]
