# Generated by Django 3.2.1 on 2021-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ex1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture_company', models.CharField(max_length=20)),
                ('models_name', models.CharField(max_length=20)),
            ],
        ),
    ]
