# Generated by Django 3.2 on 2021-05-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='chemistry',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='english',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='student',
            name='percent',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='physics',
            field=models.IntegerField(default=None),
        ),
    ]
