# Generated by Django 3.2 on 2021-05-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210505_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='percent',
        ),
    ]
