# Generated by Django 3.2.1 on 2021-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_remove_student_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='chemistry',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='english',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='physics',
            field=models.IntegerField(),
        ),
    ]
