# Generated by Django 3.2.1 on 2021-05-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='titel',
            new_name='title',
        ),
    ]
