# Generated by Django 3.2.1 on 2021-05-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ex3model',
            name='contact',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='ex3model',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ex3model',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
